profiles:
  staging:
    base_url: http://staging.liveoak.io/
    deploy:
      host: liveoak.io
      path: /var/www/domains/liveoak.io/staging/htdocs/
      uncommitted: true
  production:
    base_url: http://liveoak.io/
    google_analytics: 'UA-56523623-1'
    deploy:
      host: liveoak.io
      path: /var/www/domains/liveoak.io/www/htdocs/
      uncommitted: true

name: LiveOak
title: LiveOak
org: Red Hat
base_url: ''
asciidoctor:
  :safe: safe
  :compact: true
  :eruby: erubis
  :backend: xhtml5
  :attributes:
    idprefix: ''
    idseparator: '-'
    icons: 'font'
    sectanchors: ''
    linkattrs: ''
    source-highlighter: highlight.js
    imagesdir: /imgs

releases:
  - version: 1.0.0.Beta03
    date: 12 Mar 2015
    tar_size: 168M
    zip_size: 186M
    src_tar_size: 9.8M
    src_zip_size: 11M
  - version: 1.0.0.Beta02
    date: 18 Dec 2014
    tar_size: 159M
    zip_size: 175M
    src_tar_size: 2.2M
    src_zip_size: 3.1M
  - version: 1.0.0.Beta01
    date: 27 Oct 2014
    tar_size: 158M
    zip_size: 175M
    src_tar_size: 2.2M
    src_zip_size: 3.0M
  - version: 1.0.0.Alpha02
    date: 29 Aug 2014
    tar_size: 156M
    zip_size: 173M
    src_tar_size: 2.1M
    src_zip_size: 2.8M
  - version: 1.0.0.Alpha01
    date: 27 May 2014
    tar_size: 151M
    zip_size: 167M
    src_tar_size: 5.4M
    src_zip_size: 6.2M
