profiles:
  development:
  staging:
    base_url: http://staging.liveoak.io/
    deploy:
      host: liveoak.io
      path: /var/www/domains/liveoak.io/staging/htdocs/ 
      uncommitted: true
  production:
    base_url: http://liveoak.io/
    deploy:
      host: liveoak.io
      path: /var/www/domains/liveoak.io/www/htdocs/ 
      uncommitted: true

name: LiveOak
title: LiveOak
org: Red Hat
base_url: ''
asciidoctor:
#  :compact: true
  :eruby: erubis
  :attributes:
    idprefix: ''
    idseparator: '-'
    icons: 'font'
    sectanchors: ''
    linkattrs: ''
    source-highlighter: highlight.js
