name: LiveOak
title: LiveOak
org: Red Hat
base_url: ''
asciidoctor:
#  :compact: true
  :eruby: erubis
  :attributes:
    idprefix: ''
    idseparator: '-'
    icons: 'font'
    sectanchors: ''
    linkattrs: ''
    source-highlighter: highlight.js
